# Site wide configuration

title: Efektivní Altruismus
description: "Skupina pro podporu efektivního altruismu v ČR"
logo: ea-120.png
teaser: 400x250.gif
locale: cs_CZ

# Commented so that URLs are created relative.
# url: http://efektivni-altruismus.cz
# url: //efektivni-altruismus.cz

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist


# Octopress configuration

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: article
page_layout: article

# Format titles with titlecase?
titlecase: false


# Site owner
owner:
  name: Jiří Nádvorník
  web: http://nadvornik.org
  email: nadvornik.jiri@gmail.com
#  twitter: mmistakes
  bio: "Pokus."
#  avatar: bio-photo.jpg # 160x160 px image for author byline
  # google:
  #   plus: +MichaelRoseDesign
  #   ad-client: ca-pub-7328585512091257
  #   ad-slot: 3049671934
  # disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
